#!/usr/bin/env bash
# server-install.sh — install + start the Dinotty relay on a fresh VPS.
#
# Usage:  curl -sSL https://raw.githubusercontent.com/lovivi/dinotty/feat/windows-shell-profiles/deploy/relay/server-install.sh | sudo bash -s -- <password>
#   or:   wget -qO- ... | sudo bash -s -- <password>
#
# What it does:
#   1. Downloads the latest `dinotty-relay` binary (or builds from source
#      if no prebuilt release matches the current arch).
#   2. Generates a self-signed TLS cert (works on phones; user clicks
#      through the warning once).
#   3. Writes a systemd unit so the relay restarts on crash.
#   4. Detects the public IP and prints the line the user pastes into
#      `local-connect.sh` on the desktop.
#
# Requirements: systemd, openssl, curl or wget, sudo. Tested on Ubuntu 22.04.

set -euo pipefail

PASSWORD="${1:?usage: $0 <password>}"
if [ "${#PASSWORD}" -lt 4 ]; then
    echo "Password must be at least 4 characters" >&2
    exit 1
fi

# ---- Where to put files ----
INSTALL_DIR="/usr/local/bin"
DATA_DIR="/var/lib/dinotty-relay"
TLS_DIR="$DATA_DIR/tls"
SERVICE_NAME="dinotty-relay"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
ENV_FILE="$DATA_DIR/relay.env"

mkdir -p "$INSTALL_DIR" "$DATA_DIR" "$TLS_DIR"

# ---- Detect arch ----
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64) RELAY_ARCH="x86_64-unknown-linux-musl" ;;
    aarch64) RELAY_ARCH="aarch64-unknown-linux-musl" ;;
    *)
        echo "Unsupported arch: $ARCH (this script handles x86_64 and aarch64)" >&2
        exit 1
        ;;
esac

# ---- Download prebuilt binary ----
# The release URL pattern is /<owner>/<repo>/releases/download/relay-v<ver>/dinotty-relay-<arch>.tar.xz
# When the repo doesn't have a release yet, this 404s and we fall through
# to building from source.
REPO="${DINOTTY_REPO:-lovivi/dinotty}"
VER="${DINOTTY_VER:-latest}"
DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${VER}/dinotty-relay-${RELAY_ARCH}.tar.xz"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

echo ">> Attempting to download prebuilt relay..."
if curl -fsSL --connect-timeout 10 -o "$TMPDIR/relay.tar.xz" "$DOWNLOAD_URL" 2>/dev/null; then
    echo ">> Downloaded. Extracting..."
    tar -xJf "$TMPDIR/relay.tar.xz" -C "$TMPDIR"
    install -m 0755 "$TMPDIR/dinotty-relay" "$INSTALL_DIR/"
else
    echo ">> No prebuilt binary; building from source."
    if ! command -v cargo >/dev/null 2>&1; then
        echo "cargo not found — install rustup first:" >&2
        echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" >&2
        exit 1
    fi
    # Build only the relay crate. Assumes this script is run from a
    # clone of the repo.
    if [ ! -d "relay" ]; then
        echo "relay/ subdir not found. Run this script from the repo root," >&2
        echo "or set DINOTTY_REPO to a fork that has a relay release." >&2
        exit 1
    fi
    (cd relay && cargo build --release)
    install -m 0755 target/release/dinotty-relay "$INSTALL_DIR/"
fi

# ---- Generate self-signed TLS cert if no real one provided ----
CERT_PATH="$TLS_DIR/cert.pem"
KEY_PATH="$TLS_DIR/key.pem"
if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
    echo ">> Generating self-signed TLS cert (3650 days)..."
    openssl req -x509 -newkey rsa:4096 -days 3650 -nodes \
        -keyout "$KEY_PATH" \
        -out    "$CERT_PATH" \
        -subj "/CN=dinotty-relay.local" \
        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
        2>/dev/null
    chmod 0600 "$KEY_PATH"
    chmod 0644 "$CERT_PATH"
fi

# ---- Persist the password so the systemd unit picks it up ----
cat > "$ENV_FILE" <<EOF
# Generated by server-install.sh. Do not edit by hand.
RELAY_PASSWORD=${PASSWORD}
EOF
chmod 0600 "$ENV_FILE"

# ---- Write systemd unit ----
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Dinotty cloud relay (port auto-detect 24020-24045)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${ENV_FILE}
ExecStart=${INSTALL_DIR}/dinotty-relay --cert ${CERT_PATH} --key ${KEY_PATH}
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

# ---- Start ----
systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"
sleep 1
if ! systemctl is-active --quiet "$SERVICE_NAME"; then
    echo "!! Relay failed to start. Check: journalctl -u $SERVICE_NAME -n 50" >&2
    exit 1
fi

# ---- Detect relay port from journal ----
sleep 2
RELAY_PORT=$(journalctl -u "$SERVICE_NAME" -n 30 --no-pager 2>/dev/null | grep -oP 'port auto-selected: \K\d+' | tail -1)
RELAY_PORT="${RELAY_PORT:-24020}"

# ---- Detect public IP ----
PUBLIC_IP="$(
    curl -fsS --connect-timeout 5 https://api.ipify.org 2>/dev/null \
    || curl -fsS --connect-timeout 5 https://ifconfig.me 2>/dev/null \
    || hostname -I 2>/dev/null | awk '{print $1}' \
    || echo "127.0.0.1"
)"

# ---- Print the line the user pastes into local-connect.sh ----
cat <<EOF

============================================================
  Dinotty relay is up.

  Copy this line. On the desktop where Dinotty runs:

    curl -sSL https://raw.githubusercontent.com/${REPO}/feat/windows-shell-profiles/deploy/relay/local-connect.sh | bash -s -- "ws://${PUBLIC_IP}:${RELAY_PORT}" "\$(cat ${ENV_FILE} | grep -oP 'RELAY_PASSWORD=\\K.*')"

  Or just open the Dinotty APK on your phone, enter:
    URL:      https://${PUBLIC_IP}:${RELAY_PORT}
    Password: ${PASSWORD}
============================================================

EOF
